parallel_run_config:
  input_format:
  mini_batch_size: 1
  error_threshold: 0
  output_action: append_row
  logging_level: INFO
  compute_target_name: cpu-cluster
  node_count: 1
  process_count_per_node: 2
  entry_script: score_batch.py
  source_directory: ../../src/model1/
  description:
  run_invocation_timeout: 180
  append_row_file_name: batch-predictions.txt
  environment_name:
  environment_dir_path: parallel_run_env
